name: deploy app-chavepix

on:
  push:
    branches: [teste-ci-cd]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
      - name: Login docker hub
        run: docker login -u ${{secrets.DOCKER_LOGIN}} -p ${{secrets.DOCKER_SECRET_TOKEN}}
      - name: Docker Build
        run: docker build -t lfvilelas/app-chavepix .
      - name: Push Image Docker
        run: docker push lfvilelas/app-chavepix



